### ISSUE TITLE
How to use cordova plugin in our cordova project?

### ISSUE THREAD

**Issue by harked** [don/cordova-plugin-hello#10]
Hi All. 

I've install freshly new blank cordova project to test this plugin. Then i've just follow the step that has written in readme.md
But i still didnt know whether this plugin is working or not in my cordova project.

Here's my index.js code : 

var app = {
    initialize: function() {
        this.bindEvents();
    },

    bindEvents: function() {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },

    onDeviceReady: function() {
        var success = function(message) {
            alert(message);
        }
        var failure = function() {
            alert("Error calling Hello Plugin");
        }
        hello.greet("World", success, failure);
        
        app.receivedEvent('deviceready');
    },

    receivedEvent: function(id) {
        var parentElement = document.getElementById(id);
        var listeningElement = parentElement.querySelector('.listening');
        var receivedElement = parentElement.querySelector('.received');
        listeningElement.setAttribute('style', 'display:none;');
        receivedElement.setAttribute('style', 'display:block;');
        console.log('Received Event: ' + id);
    }
};
app.initialize();

I run/simulate it using evothings studio.

Any clue?

Thanks.

**Comment by amitsinha559** [comment]
@harked Please do like this.

instead of hello.greet please try --> window.hello.greet("World", success, failure);
