### ISSUE TITLE
alert not firing

### ISSUE THREAD

**Issue by rarutu** [don/cordova-plugin-hello#13]
Hi

I have an empty project with the default plugins ... i installed this plugin and added the call on index.js on the deviceready event but with very little luck :(
any idea what i coud be missing?

```javascript
var app = {
    initialize: function() {
        this.bindEvents();
    },
    bindEvents: function() {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },
    onDeviceReady: function() {
        app.receivedEvent('deviceready');
    },
    receivedEvent: function(id) {
        var parentElement = document.getElementById(id);
        var listeningElement = parentElement.querySelector('.listening');
        var receivedElement = parentElement.querySelector('.received');

        listeningElement.setAttribute('style', 'display:none;');
        receivedElement.setAttribute('style', 'display:block;');

        var success = function(message) {
            alert(message);
        }

        var failure = function() {
            alert("Error calling Hello Plugin");
        }
        alert('b');
        window.hello.greet("World", success, failure);

        console.log('Received Event: ' + id);
    }
};
```

btw i did not change config.xml it is in the root folder outside the www folder

thanks

**Comment by don** [comment]
Are you using iOS or Android? I tested on both and your code runs OK. I didn't test WP7.

I expect that the native code for the plugin is not installed correctly. List the plugins and ensure that `com.example.hello` is installed.

    $ cordova plugin ls
    com.example.hello 0.7.0 "Hello"
    cordova-plugin-whitelist 1.0.0 "Whitelist"

If it's not installed, use cordova (or phonegap) to install the plugin.

    $ cordova plugin add /path/to/where/you/cloned/cordova-plugin-hello
