### ISSUE TITLE
how to use jni with cordova

### ISSUE THREAD

**Issue by anshuvij** [don/cordova-plugin-hello#14]
can u pls provide a simple jni project with cordova calling c++ function?

**Comment by don** [comment]
I think the [Crosswalk Project](https://crosswalk-project.org/documentation/cordova.html) uses JNI in their Cordova plugin. I'd suggest looking at their source code.

**Comment by brodybits** [comment]
A couple other examples:

- https://github.com/AllJoyn-Cordova/cordova-plugin-alljoyn
- https://github.com/litehelpers/cordova-sqlite-ext and https://github.com/litehelpers/Cordova-sqlcipher-adapter which I maintain

**Comment by don** [comment]
Thanks @brodybits
