### ISSUE TITLE
iOS build failed with latest cordova

### ISSUE THREAD

**Issue by neilyoung** [don/cordova-plugin-hello#15]
llo.m:16:11: error: 
      no visible @interface for 'HWPHello' declares the selector 'success:callbackId:'
    [self success:result callbackId:callbackId];
     ~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

** BUILD FAILED **

**Comment by neilyoung** [comment]
Proper handling would be like shown here:

https://cordova.apache.org/docs/en/latest/guide/platforms/ios/plugin.html

This git is outdated

**Comment by 28formica77** [comment]
This looks like the same issue, I had
[self.commandDelegate sendPluginResult:result callbackId:callbackId];

**Comment by don** [comment]
Fixed by #18
