### ISSUE TITLE
How can I get multiple responses for one request?

### ISSUE THREAD

**Issue by Kushi171987** [don/cordova-plugin-hello#17]
In my application, I called this method
`    hello.greet("World", success, failure);
`
So I get only one response from the native, even I added a for loop to send multiple responses on iOS side.
`for (int i = 0; i <=5; i++) {
      [self.commandDelegate sendPluginResult:result callbackId:callbackId];
  }`

**Comment by don** [comment]
If you're going to call a callback multiple times, you need to set `setKeepCallbackAsBool` to TRUE on the PluginResult before sending. See https://github.com/don/BluetoothSerial/blob/master/src/ios/MEGBluetoothSerial.m#L240

**Comment by Kushi171987** [comment]
Its working fine :+1: 
Thank you.
