### ISSUE TITLE
can you improve a jni example?

### ISSUE THREAD

**Issue by yaonie084** [don/cordova-plugin-hello#5]
your example had help me create a custom plugin few days ago, thanks. I think it's very useful.

but it's not enough for me, I need a JNI example, that would be great for me. Thanks in advance.

**Comment by partus** [comment]
Great! thanks for simple demonstration!

**Comment by fabiomig** [comment]
Yeah it would be cool if you can show us how to

**Comment by don** [comment]
For JNI, I'd work with the [Android NDK](https://developer.android.com/tools/sdk/ndk/index.html) and get a simple JNI example working **without** Cordova.

Once you have the JNI example working, you should be able to add it to a Cordova plugin. Javascript will still call a Java class (e.g. Hello.java) and your Java class will make the JNI call.
