### ISSUE TITLE
Uncaught ReferenceError: hello is not defined

### ISSUE THREAD

**Issue by BenjaminHorn** [don/cordova-plugin-hello#9]
I followed the instructions but I'am getting:

>file:///data/data/com.adobe.phonegap.app/files/files/phonegapdevapp/www/js/index.js:45
Uncaught ReferenceError: hello is not defined

at
```javascript
hello.greet("World", success, failure);
```

Phonegap: 5.1.1-0.29.0 (cordova: 5.1.1 )
Android: 4.3
I use Phonegap Developer App and www.jsconsole.com to debug.

**Comment by don** [comment]
@BenjaminHorn you can't use this plugin with PhoneGap Developer App. PhoneGap Developer App only works with plugins that were installed when the app was built. https://github.com/phonegap/phonegap-app-developer/tree/master/plugins

**Comment by BenjaminHorn** [comment]
@don thanks. I'm new to phonegap;) Then what is the best way debug / try out an app?
```
phonegap build
```

and then copy the apk to the device, and run it? Sounds cumbersome.
